Feature/ubi 297 pathfinding manager
Ubivius/ubivius-game pull request #22
Opened 2021-02-14 03:01 UTC by Daftdoritos

#### Quel changement ça apporte?
Ajout du Manager pour gérer le pathfibnding et la grille d'une pièce donné du jeu
#### Quels JIRA sont concernés?
UBI-297

#### Comment ça a été testé (étapes pour reproduire les tests du côté des reviewers)?
Aucun test

#### Notes pour les reviewers
Pas encore terminé, il s'agit d'avoir un premier avis

@ubivius/gamedev

2021-02-14 20:45 UTC, shortChangeDev requested changes
Voir commentaires + En tant que user, je m'attendrais à avoir une interface pour récupérer des paths complets, mettons comme GetPath(...). Genre juste plugger les fils de Pathfinding vers PathfindingManager

2021-02-14 20:45 UTC, shortChangeDev commented on Assets/Scripts/Common/World/WorldGenerator.cs
> +        private PathfindingGridManager m_pathfindingGridManager;
Je préfère que ça soit externe au World Generator. 
C'est pas la responsabilité du World Generator de connaître le pathfinding Manager, c'est l'inverse selon moi.
(C'est le Pathfinding Manager qui a le rôle de connaître le World Generator)

2021-02-14 20:45 UTC, shortChangeDev commented on Assets/Scripts/Pathfinding/PathfindingGridManager.cs
> +        if (x >= 0 && y >= 0 && x < m_logicGrid.GetWidth() && y < m_logicGrid.GetHeight() && m_pathNodeList.Contains(new PathNode(x, y)))
La condition Contains(...) sera TOUJOURS fausse parce que tu crées une nouvelle PathNode qui par défintion n'existe pas dans m_pathNodeList

2021-02-14 20:45 UTC, shortChangeDev commented on Assets/Scripts/Pathfinding/PathfindingGridManager.cs
> +            if (pathnode.GetNeighbourList().Contains(null))
Pas besoin du if ici, RemoveAll s'en occupe

2021-02-20 23:34 UTC, Daftdoritos commented on Assets/Scripts/Common/World/WorldGenerator.cs
> +        private PathfindingGridManager m_pathfindingGridManager;
Ok, ça sera la même chose pour les autres managers? J'en avais parlé à Jérôme et il avait dit quil pluggerait les managers dans le world generator.... mais je croisn que ce que tu dis fait plus de sens

2021-02-21 00:47 UTC, shortChangeDev commented on Assets/Scripts/Common/World/WorldGenerator.cs
> +        private PathfindingGridManager m_pathfindingGridManager;
Oui, le principe reste valide pour les autres.

2021-02-21 06:10 UTC, Daftdoritos commented on Assets/Scripts/Pathfinding/PathfindingGridManager.cs
> +        if (x >= 0 && y >= 0 && x < m_logicGrid.GetWidth() && y < m_logicGrid.GetHeight() && m_pathNodeList.Contains(new PathNode(x, y)))
C'est initialisé dans le constructeur... jai changé par contre l'accessibilité de la fonction a private

2021-02-24 18:56 UTC, shortChangeDev requested changes

2021-02-24 18:56 UTC, shortChangeDev commented on Assets/Scripts/Common/World/WorldGenerator.cs
> +        private PathfindingGridManager m_pathfindingGridManager;
Même commentaire qu'avant : pense pas que ça soit la job du WorldGenerator d'avoir ce manager-là

2021-02-24 18:56 UTC, shortChangeDev commented on Assets/Scripts/Pathfinding/PathfindingGridManager.cs
> +public class PathfindingGridManager
Pas oublier les namespace (ici probablement ubv.server.world)

2021-02-24 18:56 UTC, shortChangeDev commented on Assets/Scripts/Pathfinding/Testing.cs
> +    private List<PathNode> path;
m_path au lieu de path

2021-02-24 18:56 UTC, shortChangeDev commented on Assets/Scripts/Pathfinding/Testing.cs
> +public class Testing : MonoBehaviour
Attention : nom de la classe est extrêmement vague

2021-03-04 23:01 UTC, shortChangeDev commented on Assets/Scripts/Pathfinding/PathfindingGridManager.cs
> +    [SerializeField] private WorldGenerator m_worldGenerator;
Attention : le jour ou on voudra faire du _pathfinding_ sur une Grid qui ne sera pas membre de WorldGenerator, on va devoir modifier ça. Peut-être faire une interface à la place, qui présente une seule fonction : `LogicGrid GetLogicGrid();` ?
C'est pas la fin du monde de le garder comme ça, mais j'écris ça pour qu'on s'en souvienne au cas où on rencontrerais la situation.

2021-03-04 23:01 UTC, shortChangeDev approved these changes
Looks good; voir commentaire sur PathfindingManager, sinon tout est beau

2021-03-07 02:15 UTC, JerPaq approved these changes

2021-03-07 04:55 UTC, merged