Feature/ubi 234 microservice http comms
Ubivius/ubivius-game pull request #26
Opened 2021-03-01 16:55 UTC by shortChangeDev

#### What changes does this PR contain?
Adds an interface to manage HTTP requests (to microservices) and subscribe to responses

#### Which JIRA ticket ID's are associated with this PR?
UBI-234

#### How was it tested (Steps to reproduce by reviewers)?
Start Docker
Write http requests (PUT, GET, DELETE, POST) from somewhere in the code (calling methods from HTTPClient)
Such as 
```
Debug.Log(Get("products"));
PostJSON("products", "{\"name\":\"New Object added by Murphy\", \"price\":69.69, \"sku\":\"abc-abc-abcd\"}");
Debug.Log(Get("products"));
```
Start the client

#### Notes for reviewers
- 
@ubivius/gamedev

2021-03-01 18:28 UTC, ysma500 requested changes
Could there be a test file with a mocked http server created for unit testing with this lib?

2021-03-01 18:28 UTC, ysma500 commented on Assets/Scripts/HTTPToolkit/HTTPClient.cs
> +}
No new line EOF

2021-03-01 18:28 UTC, ysma500 commented on Assets/Scripts/HTTPToolkit/HTTPClient.cs
> +        public HttpResponseMessage Put(string requestUrl, string jsonString)
Why not PutJSON like the PostJSON function name?

2021-03-01 21:16 UTC, JerPaq submitted a review, later dismissed

2021-03-02 18:58 UTC, shortChangeDev commented on Assets/Scripts/HTTPToolkit/HTTPClient.cs
> +        [SerializeField] string m_endPoint = "http://localhost:9090";
private par défaut, mais je vais le rajouter quand même, merci!

2021-03-03 23:49 UTC, Daftdoritos approved these changes

2021-03-04 03:24 UTC, ArcticWalrus approved these changes
Ça semble bon. On va devoir y apporter des changements quand on ajoute l'authentification aux microservices mais d'ici là c'est bon

2021-03-04 03:26 UTC, ArcticWalrus commented
Il reste juste à fix le CI avant

2021-03-06 21:49 UTC, ysma500 approved these changes
LGTM

2021-03-06 21:50 UTC, merged