Feature/ubi 351 load world true async
Ubivius/ubivius-game pull request #33
Opened 2021-03-14 01:02 UTC by shortChangeDev

#### What changes does this PR contain?
Adds a loading screen between lobby and play (during client world loading )

#### Which JIRA ticket ID's are associated with this PR?
UBI-351

#### How was it tested (Steps to reproduce by reviewers)?
Start client
Start server
Client:  Connect to server
Server: Force start game
Client: loading screen displays load percentage

#### Notes for reviewers

@ubivius/gamedev

2021-03-14 16:19 UTC, JerPaq requested changes
mon dieu j'en reviens pas que t'as pas mis de ligne à la fin d'un ficher, honte à vous.

2021-03-14 16:19 UTC, JerPaq commented on Assets/Scripts/UI/Client/LoadingScreen.cs
> +}
AH! J'AI TROUVÉ DE QUOI. il te manque une ligne à la fin du file

2021-03-14 16:21 UTC, shortChangeDev commented on Assets/Scripts/UI/Client/LoadingScreen.cs
> +}
Zut, j'étais certain de les avoir tous attrapés
merci!

2021-03-14 16:23 UTC, JerPaq approved these changes

2021-03-15 17:38 UTC, Daftdoritos approved these changes

2021-03-15 17:41 UTC, merged