Feature/ubi 367 draft gamemaster
Ubivius/ubivius-game pull request #49
Opened 2021-04-06 17:46 UTC by JerPaq

#### What changes does this PR contain?
Juste un nouveau fichier, sinon rien de gros. Une ligne en commentaire à été ajouter comme note pour ma prochaine tâche.

#### Which JIRA ticket ID's are associated with this PR?
http://ysma500.asuscomm.com:6969/browse/UBI-367
#### How was it tested (Steps to reproduce by reviewers)?
only a new file
#### Notes for reviewers
AIDIWWWNMW
@ubivius/gamedev

2021-04-06 18:17 UTC, Daftdoritos approved these changes
C'est normal que les fonctions du file soient vides?

2021-04-06 18:19 UTC, JerPaq commented
> 
> 
> C'est normal que les fonctions du file soient vides?

Oui, c'est les fonctions qui viennent de l'héritage à l'autre class, pour l'instant il y a rien ils vont être remplis plus tard

2021-04-06 23:57 UTC, shortChangeDev requested changes
Tant qu'à avoir le script là, je rajouterais un GameObject GameMaster à la scène côté serveur pis je le mettrais dans les updaters tout de suite.

2021-04-07 01:56 UTC, JerPaq commented
> 
> 
> Tant qu'à avoir le script là, je rajouterais un GameObject GameMaster à la scène côté serveur pis je le mettrais dans les updaters tout de suite.

c'est déjà dans la branche que je travaille pour l'autre tâche

2021-04-07 02:10 UTC, shortChangeDev approved these changes

2021-04-08 12:59 UTC, merged