Pathfinding
Ubivius/ubivius-game pull request #6
Opened 2021-01-27 22:22 UTC by Daftdoritos

2021-01-28 16:17 UTC, JerPaq requested changes
Fec la majorité de mes comments c'est des questions vue qu'il va falloir que je fasse un système de map qui va marcher avec le pathfinding. Je veux être sur de bien comprendre où on s'en va.

2021-01-28 16:17 UTC, JerPaq commented on Assets/Scripts/Pathfinding/PathNode.cs
> +    private Grid<PathNode> grid;
va me falloir un cours de Grid<> les chevron permet quoi, et je sais pas si avoir une classe qui a le même nom qu'on component de base est correct.

2021-01-28 16:17 UTC, JerPaq commented on Assets/Scripts/Pathfinding/PathNode.cs
> +    public int x;
private avec un m_ si c'est pas obliger d'être public

2021-01-28 16:17 UTC, JerPaq commented on Assets/Scripts/Pathfinding/Grid.cs
> +                gridArray[x, y] = createGridObject(this, x, y);
Pour ma compréhension, tu importe une fonction et cette fonction crée les node et les met dans la grid, est-ce que c'est nécessaire que le node est une référence à la grid? j'ai peur que ça créer une sorte de référence circulaire.

2021-01-28 16:17 UTC, JerPaq commented on Assets/Scripts/Pathfinding/PathNode.cs
> +    public PathNode(Grid<PathNode> grid, int x, int y) {
Même chose quand haut, est-ce qu'il a besoin d'avoir la grid en référence.

2021-01-28 16:17 UTC, JerPaq commented on Assets/Scripts/Pathfinding/Pathfinding.cs
> +    private Grid<PathNode> grid;
petit m_

2021-01-28 16:17 UTC, JerPaq commented on Assets/Scripts/Pathfinding/Pathfinding.cs
> +        List<PathNode> path = FindPath(startX, startY, endX, endY);
J'ai rien contre le récursif, mais je sais pas si c'est propre d'appeler une surcharge de sois même, est-ce que les 2 fonctions doivent avoir le même nom vue qu'ils ne font pas la même chose?

2021-01-28 16:17 UTC, JerPaq commented on Assets/Scripts/Pathfinding/Pathfinding.cs
> +                pathNode.gCost = 99999999;
comprends pas le 99999999 (plus le concept de gCost et hCost que je ne suis pas sur)

2021-01-28 16:51 UTC, Daftdoritos commented on Assets/Scripts/Pathfinding/Pathfinding.cs
> +                pathNode.gCost = 99999999;
Pour initialiser le cout de mes nodes a infini

2021-01-28 16:54 UTC, Daftdoritos commented on Assets/Scripts/Pathfinding/Pathfinding.cs
> +        List<PathNode> path = FindPath(startX, startY, endX, endY);
Je vais changer le nom des fonctions car ya deux FindPath avec arguments différents

2021-01-28 16:58 UTC, Daftdoritos commented on Assets/Scripts/Pathfinding/PathNode.cs
> +    private Grid<PathNode> grid;
La grid contient des Pathnodes

2021-01-28 16:59 UTC, Daftdoritos commented on Assets/Scripts/Pathfinding/PathNode.cs
> +    public int x;
jen ai de besoins thats why

2021-01-28 16:59 UTC, Daftdoritos commented on Assets/Scripts/Pathfinding/PathNode.cs
> +    public int x;
pourrait faire un get aussi mais je ne trouvais pas ça necessaire

2021-01-28 19:02 UTC, JerPaq commented on Assets/Scripts/Pathfinding/PathNode.cs
> +    public int x;
@shortChangeDev moi j'aime bien les properties, si toi tu es d'accord avec juste un public je vais vous laisser le contrôle

2021-01-28 20:06 UTC, shortChangeDev requested changes
Outre la mise en forme (les m_ et les majuscules etc.), il y a quelques trucs au niveau de la responsabilité du code, de la performance et de la pertinence de certains éléments.  J'ai écris entre autres sur e la façon dont j'ai codé ça par le passé et ça influence certainement mon jugement. J'aime mieux ma façon de faire, mais il y a peut-être des choses qui m'ont échappées. N'hésite pas à me poker pour qu'on en jase,

2021-01-28 20:06 UTC, shortChangeDev commented on Assets/Scripts/Pathfinding/Pathfinding.cs
> +    public List<PathNode> FindPath(int startX, int startY, int endX, int endY)
Est-ce qu'on veut exposer cette version-ci ? Je ne pense pas que l'utilisateur doive être au courant de l'existence de la classe PathNode.

2021-01-28 20:06 UTC, shortChangeDev commented on Assets/Scripts/Pathfinding/Pathfinding.cs
> +    public PathNode GetNode(int x, int y)
Voir mon commentaire sur FindPath

2021-02-01 06:42 UTC, Daftdoritos commented on Assets/Scripts/Pathfinding/Grid.cs
> +        for (int x = 0; x < gridArray.GetLength(0); x++)
Well j'ai pas trouvé d'autres fonctions qui peuvent faire cela

myArray.GetLength(0)  -> Gets first dimension size

myArray.GetLength(1)  -> Gets second dimension size

2021-02-01 06:45 UTC, Daftdoritos commented on Assets/Scripts/Pathfinding/Pathfinding.cs
> +    private List<PathNode> openList;
Well ça m'aidait juste a visualiser mes trucs... je peux l'enlever

2021-02-01 06:54 UTC, Daftdoritos commented on Assets/Scripts/Pathfinding/Grid.cs
> +            return default(TGridObject);
elle va retourner l'objet qui est initialiser par defaut a nul.. je peux juste retourner null i guess

2021-02-01 14:22 UTC, shortChangeDev commented on Assets/Scripts/Pathfinding/Grid.cs
> +        for (int x = 0; x < gridArray.GetLength(0); x++)
Ce que je veux dire c'est que caller `gridArray.GetLength(0)` c'est **exactement** la même chose que de caller `width` sauf que c'est moins clair et moins efficace. Tu connais déjà la valeur de `gridArray.GetLength(0)` : c'est `width`. Sauf qu'en callant la fonction au lieu de direct la valeur, tu ajoutes un niveau d'indirection, parce que le tableau doit passer par GetLength.

2021-02-01 14:23 UTC, shortChangeDev commented on Assets/Scripts/Pathfinding/Grid.cs
> +            return default(TGridObject);
Si TGridObject est un int, elle va retourner zéro. Si TGridObject est un Vector3, elle va retourner Vector3.zero.
Bref, si l'object n'est pas un nullable type, ça ne retourne pas null.

2021-02-01 14:24 UTC, shortChangeDev commented on Assets/Scripts/Pathfinding/Pathfinding.cs
> +    private List<PathNode> openList;
Ce n'est pas le fait qu'elles existent que je remets en question, c'est leur présence dans l'espace "classe" plutôt que dans l'espace "fonction". La classe n'a pas besoin de savoir qu'elles existent. Seule la fonction en a le besoin.

2021-02-03 05:23 UTC, Daftdoritos commented on Assets/Scripts/Pathfinding/Grid.cs
> +            return default(TGridObject);
Ok, so je retourne quoi?

2021-02-03 13:34 UTC, shortChangeDev commented on Assets/Scripts/Pathfinding/Grid.cs
> +            return default(TGridObject);
Juste null, selon moi.

2021-02-03 17:52 UTC, Daftdoritos commented on Assets/Scripts/Pathfinding/Grid.cs
> +            return default(TGridObject);
![image](https://user-images.githubusercontent.com/36829260/106788220-ad735180-661e-11eb-85f0-79fbf58852e6.png)

2021-02-03 17:53 UTC, Daftdoritos commented on Assets/Scripts/Pathfinding/Grid.cs
> +            return default(TGridObject);
anyway je suis pas mal entrain de modifier l'algo pour qu'il soit plus perfromant

2021-02-03 17:54 UTC, shortChangeDev commented on Assets/Scripts/Pathfinding/Grid.cs
> +            return default(TGridObject);
Oh right c'est vrai! Tu peux pas retourner null vu que c'est pas un nullable type, my bad!
Reste que j'aime moyen qu'on retourne quelque chose alors qu'il n'y a peut-être rien... C'est tricky. 
Je vais être sur Discord une partie du PM, si tu veux qu'on en jase

2021-02-03 17:57 UTC, Daftdoritos commented on Assets/Scripts/Pathfinding/Grid.cs
> +            return default(TGridObject);
je suis en lab tho...

2021-02-06 21:08 UTC, shortChangeDev requested changes

2021-02-06 21:08 UTC, shortChangeDev commented on Assets/Scripts/Pathfinding/PathNode.cs
> +    public int fCost;
Je suis moyen à l'aise d'exposer gCost, hCost et fCost au public, surtout puisqu'elles ne sont utilisées que la par classe Pathfinding. Rien n'empêche un user extérieur de modifier le gCost au beau milieu de nulle part depuis l'autre bout du code, et ça ça va faire chier le pathfinding.
Ce que je ferais, c'est que je garderais PathNode comme un moyen d'interface avec le pathfinding, mais je créerais une structure Cost { qui contient les costs int g, h, f - by the way, les noms sont pas ben ben clair, ça serait pertinent de les renommer en quelque chose de plus explicite } et ensuite un Dictionary<PathNode, Cost> dans la classe Pathfinding elle même, et je jouerais avec ce Dict là seulement. Comme ça, le user n'y a pas accès et peut quand même avoir une référence sur la Node.

2021-02-06 21:08 UTC, shortChangeDev commented on Assets/Scripts/Pathfinding/PathNode.cs
> +    }
Ultimement, en tant que user, je veux pouvoir créer les nodes, leur setter des voisins et les modifier au run time, par exemple enlever un voisin d'une node. 
Il faudrait ajouter cette interface-là. AddNeighbour, RemoveNeighbour, par exemple.
Également, ça pourrait être pertinent d'être capable de set un cost additionnel à la node, pour représenter mettons des sables mouvants ou whatever truc qui ralentit le déplacement mais qui ne l'empêche pas. Live, tous les couts des nodes sont les même à la base.

2021-02-07 04:50 UTC, shortChangeDev approved these changes

2021-02-07 15:04 UTC, merged