Feature/ubi 461 networking integration enemy
Ubivius/ubivius-game pull request #91
Opened 2021-11-03 05:06 UTC by Daftdoritos

#### What changes does this PR contain?
Systeme d'AI d'ennemies en réseau, il Spawn, mais il y a du jitter coté client pour le deplacement de ceux-ci
#### Which JIRA ticket ID's are associated with this PR?

#### How was it tested (Steps to reproduce by reviewers)?
Start server and client and in the Enemy server updaters, set nb of enemys for the scene. they are moving in random directions in the map
#### Notes for reviewers

@ubivius/gamedev

2021-11-08 21:41 UTC, JeremiSavard reviewed
je ferais le tour pour enlever le code commenté

2021-11-08 21:41 UTC, JeremiSavard commented on Assets/Scripts/Client/EnemyGameObjectUpdater.cs
> +        }
si c'est tout en commentaire, est-ce possible de l'enlever ?

2021-11-08 21:41 UTC, JeremiSavard commented on Assets/Scripts/Common/EnemyStateData.cs
> +                }*/
enlever ca aussi si tu peux

2021-11-08 22:42 UTC, shortChangeDev requested changes
Il y a beaucoup, beaucoup de code ici qui est pêle-mêle. Je pense que ça serait une bonne idée de faire le ménage à la fois dans le code qui n'est plus pertinent ou commenté ET dans les responsabilités de chaque classe.

2021-11-08 22:42 UTC, shortChangeDev commented on Assets/Scripts/Client/PlayerGameObjectUpdater.cs
> -                player.States.Set((int)PlayerStateEnum.IS_SPRINTING, m_isSprinting[player.GUID.Value]);
Pourquoi est-ce qu'on modifie la logique de sprint dans cette PR ?

2021-11-08 22:42 UTC, shortChangeDev commented on Assets/Scripts/Client/EnemyGameObjectUpdater.cs
> +        }
+1

2021-11-08 22:42 UTC, shortChangeDev commented on Assets/Scripts/EnemySystem/EnemyMain.cs
> +public class EnemyMain : MonoBehaviour
Pas de namespace; 
Est-ce que le fichier était utilisé pour tester  ? Si oui, le supprimer

2021-11-08 22:42 UTC, shortChangeDev commented on Assets/Scripts/EnemySystem/EnemyPathFindingMovement.cs
> +public class EnemyPathFindingMovement : MonoBehaviour
Pas de namespace

2021-11-08 22:42 UTC, shortChangeDev commented on Assets/Scripts/ScriptableObjects/EnemySettings.cs
> +}
Line at EOF

2021-11-08 22:42 UTC, shortChangeDev commented on Assets/Scripts/PlayerControls.cs
> -    private int m_AllControlSchemesSchemeIndex = -1;
Pourquoi est-ce que les PlayerControls sont modifiés dans cette PR ? Erreur de merge ?

2021-11-08 22:42 UTC, shortChangeDev commented on Assets/Scripts/EnemySystem/Utils.cs
> +public static class Utils
Pas de namespace

2021-11-08 22:42 UTC, shortChangeDev commented on Assets/Scripts/EnemySystem/Utils.cs
> +{
Pas certain que cette classe-là aie sa place dans EnemySystem. Peut-être davantage dans Scripts/Common ?

2021-11-08 22:42 UTC, shortChangeDev commented on Assets/Scripts/EnemySystem/GenerateEnemies.cs
> +    {
On a pas déjà une classe qui s'occupe de générer les ennemis ? EnemyBehaviourUpdater non ?

2021-11-08 22:42 UTC, shortChangeDev commented on Assets/Scripts/EnemySystem/EnemyStatePattern/EnemyState.cs
> +    abstract public class EnemyState: common.serialization.Serializable
Je ne suis pas certain de comprendre la pertinence de faire hériter les EnemyState de Serializable. Pourquoi voudrait-on les passer à travers le réseau ? Ce qu'on veut, si je ne m'abuse, c'est communiquer l'état physique de l'ennemi, pas son état comportemental, non ?

2021-11-08 22:42 UTC, shortChangeDev commented on Assets/Scripts/EnemySystem/EnemyStatePattern/EnemyStateMachine.cs
> +        public EnemyState CurrentEnemyState;
Pourquoi est-ce que le CurrentEnemyState est public ?

2021-11-08 22:42 UTC, shortChangeDev commented on Assets/Scripts/Client/EnemyGameObjectUpdater.cs
> +        [SerializeField] private float m_lerpTime = 0.2f;
Je ne suis pas certain de comprendre les responsabilités de toutes les classes et j'ai l'impression que certaines se chevauchent : on a EnemyGameObjectUpdater, EnemyBehaviourUpdater, GenerateEnemies et EnemyPathFindingMovement qui se partagent les rôles de faire spawn les ennemis, trouver leur prochaine destination et les faire se déplacer. 
Ça donne du code qui est très difficile à débugger, parce qu'on se perd dans qui fait quoi et qui devrait faire quoi.
Ça serait pertinent, je pense, de faire l'exercice de résumer le rôle principal de chaque classe et de découpler les rôles partagés par plusieurs classes. Je vois ces rôles-ci:

- Faire apparaître les ennemis
- Déterminer leur objectif de déplacement
- Les faire se déplacer vers un objectif
- (éventuellement, modifier leur état comportemental)

Une classe peut avoir plusieurs rôles, mais un rôle ne peut pas être partagé entre plusieurs classes.

2021-11-08 22:48 UTC, JerPaq reviewed
question syntaxe pas vue grand chose à part les gros bout de commentaire, autre celui qui va peut-être gérer la vie et les dégâts, retirer les bloc inutile pour moins être mêler si on y retourne d'ici la fin du moi.

2021-11-08 22:48 UTC, JerPaq commented on Assets/Scripts/EnemySystem/GenerateEnemies.cs
> +}
git dit qu'il manque une ligne

2021-11-08 22:48 UTC, JerPaq commented on Assets/Scripts/ScriptableObjects/EnemySettings.cs
> +}
ligne

2021-11-09 01:07 UTC, Daftdoritos commented on Assets/Scripts/Client/PlayerGameObjectUpdater.cs
> -                player.States.Set((int)PlayerStateEnum.IS_SPRINTING, m_isSprinting[player.GUID.Value]);
no idea

2021-11-09 01:08 UTC, Daftdoritos commented on Assets/Scripts/EnemySystem/EnemyMain.cs
> +public class EnemyMain : MonoBehaviour
Ouais il est utilisé

2021-11-09 01:12 UTC, Daftdoritos commented on Assets/Scripts/EnemySystem/GenerateEnemies.cs
> +    {
ouais c'est plus un fichier de test pour la scene protomap

2021-11-09 05:16 UTC, Daftdoritos commented on Assets/Scripts/EnemySystem/EnemyStatePattern/EnemyState.cs
> +    abstract public class EnemyState: common.serialization.Serializable
Ouais... en bout de ligne je voir pas l'utilité de communiquer l'état au client...

2021-11-09 05:21 UTC, Daftdoritos commented on Assets/Scripts/Client/EnemyGameObjectUpdater.cs
> +        [SerializeField] private float m_lerpTime = 0.2f;
-Enemybehaviorupdater est le updater du coté serveur: il initialise les ennemis et envoie les données pertinentes aux clients

-EnemyGameObjectUpdater s'occupe de s'updater sur l'état du serveur pour les enemis client
-EnemyPathFindingMovement s'occupe de handler le mouvement des enemies ca se passe coté serveur
-EnemyStateMachine s'occupe de passer a travers le états de ennemis coté serveur
-EnemyMovement est un script pour deplacer les enemies dans le client en fonction des données envoyées par le serveur

2021-11-10 16:14 UTC, shortChangeDev approved these changes
Reste juste à rajouter le namespace, mais suite à notre conversation de l'autre jour, LGTM

2021-11-10 16:14 UTC, shortChangeDev commented on Assets/Scripts/EnemySystem/EnemyMain.cs
> +public class EnemyMain : MonoBehaviour
c'est toujours pas englobé dans un namespace :P

2021-11-10 20:06 UTC, JerPaq approved these changes

2021-11-10 23:53 UTC, closed without merging