minor/hotfix/UBI-556-fixTagGameDev
Ubivius/ubivius-game pull request #97
Opened 2021-11-10 02:38 UTC by JeremiSavard

#### What changes does this PR contain?
Fix the images tag on dockerhub
#### Which JIRA ticket ID's are associated with this PR?
ubi-556
#### How was it tested (Steps to reproduce by reviewers)?
open a PR and pray it generates the tag 0.0.0-rc
#### Notes for reviewers

@ubivius/gamedev

2021-11-10 04:05 UTC, JeremiSavard commented
@ysma500 avec mes changements sa génère le tag "0.0.0-rc0". Est-ce qu'on garde ca ? je sais que en ce moment quand on delete le pod du serveur de jeu il va pull l'image qui s'appelle "dev".

2021-11-13 21:50 UTC, ysma500 requested changes

2021-11-13 21:50 UTC, ysma500 commented on .github/workflows/pr-dev.yml
> +          tags: "${{ env.REPO_VERSION }}"
I just found the issue by looking at your PR, it should have been steps.fetch-vars.outputs instead of steps.fetch-DOCKER-vars.outputs

2021-11-13 21:50 UTC, ysma500 commented on .github/workflows/pr-dev.yml
> +          tags: "${{ env.REPO_VERSION }}"
I'll do a commit on your branch and thumbs it up

2021-11-13 21:58 UTC, ysma500 commented
> @ysma500 avec mes changements sa génère le tag "0.0.0-rc0". Est-ce qu'on garde ca ? je sais que en ce moment quand on delete le pod du serveur de jeu il va pull l'image qui s'appelle "dev".

Yes, we keep it that way to enable the dev team to test 'em... We cloud clarify maybe with a tag "dev-rc0"? WDYT @JeremiSavard  ?

2021-11-13 22:34 UTC, ysma500 approved these changes
LGTM

2021-11-13 22:45 UTC, ArcticWalrus approved these changes

2021-11-13 22:46 UTC, merged